services:
  db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
